name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Remove dist folder
        run: |
          if [ -d "dist" ]; then
            rm -rf dist
          fi

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: gh-pages
          folder: dist

      - name: Cleanup
        run: |
          if [ -d "dist" ]; then
            rm -rf dist
          fi
