name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - website/**
      - .github/workflows/deploy.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd website
          npm ci

      - name: Build project
        run: |
          cd website
          npm run build

      - name: Generate 404.html
        run: |
          cd website
          repo_name=$(git rev-parse --show-toplevel | xargs basename)
          echo "<!DOCTYPE html><html lang="es"><head><meta http-equiv='refresh' content='0; url=https://pabcrudel.github.io/$repo_name/'></head></html>" > dist/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: gh-pages
          folder: website/dist
