name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm install -g clean-css-cli

      - name: Build project
        run: npm run build

      - name: Minify public css
        run: |
          while read -d $'\0' file; do
            cleancss "$file" -o "$file" --compatibility "ie >= 11, Edge >= 12, Firefox >= 2, Chrome >= 4, Safari >= 3.1, Opera >= 15, iOS >= 3.2"
          done < <(find . -type f -name "*.css")

      - name: Generate 404.html
        run: |
          repo_name=$(git rev-parse --show-toplevel | xargs basename)
          echo "<!DOCTYPE html><html lang="es"><head><meta http-equiv='refresh' content='0; url=https://pabcrudel.github.io/$repo_name/'></head></html>" > dist/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: gh-pages
          folder: dist
